AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  CloudthreadAccount:
    Type: String
    AllowedPattern: "^[0-9]{12}$"
  ExternalId:
    Type: String
    AllowedPattern: "^.*$"
    Description: "A set of characters of your choice (any length, alfanumeric characters) - this is for verification purposes, so that we know you are the owner of the role that is getting created by CloudFormation. Make sure this ID is not available to the public."
Resources:
  CloudthreadAccess:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${CloudthreadAccount}:root"
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId
      Path: "/"
  RolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "cloudthread-cost-explorer-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ce:DescribeCostCategoryDefinition"
              - "ce:GetRightsizingRecommendation"
              - "ce:GetCostAndUsage"
              - "ce:GetSavingsPlansUtilization"
              - "ce:GetAnomalies"
              - "ce:GetReservationPurchaseRecommendation"
              - "ce:GetCostForecast"
              - "ce:GetPreferences"
              - "ce:GetReservationUtilization"
              - "ce:GetCostCategories"
              - "ce:GetSavingsPlansPurchaseRecommendation"
              - "ce:GetDimensionValues"
              - "ce:GetSavingsPlansUtilizationDetails"
              - "ce:GetAnomalySubscriptions"
              - "ce:GetCostAndUsageWithResources"
              - "ce:DescribeReport"
              - "ce:GetReservationCoverage"
              - "ce:GetSavingsPlansCoverage"
              - "ce:GetAnomalyMonitors"
              - "ce:DescribeNotificationSubscription"
              - "ce:GetTags"
              - "ce:GetUsageForecast"
            Resource: "*"
      Roles:
        - Ref: "CloudthreadAccess"
Outputs:
  IamRoleArn:
    Value: !GetAtt CloudthreadAccess.Arn
  ExternalId:
    Value: !Ref ExternalId
